### ISSUE TITLE
Link name is incorrect in prerequisites

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-array-methods#2]
```diff
--   [ga-wdi-boston/ruby-vs-js-arrays](https://github.com/ga-wdi-boston/ruby-arrays)
+-   [ga-wdi-boston/ruby-arrays](https://github.com/ga-wdi-boston/ruby-arrays)
```

@jrhorn424 I would actually much prefer we use actual titles here, i.e "Ruby Array".  I know we discussed this before, but could we revisit?

**Comment by jrhorn424** [comment]
@gaand I'm happy to revisit. My objection, and it is mild, is that linking to actual repos is what we do (and probably should do?) in diagnostics, so I favor that only for consistency.

A possible rebuttal would be that we not name the links section in diagnostics "Prerequisites", and instead use actual titles there, and add a section called "Reference Material" to link to the actual repositories.

**Comment by gaand** [comment]
I'm just trying to use links in our readmes as they are used on the web.  Usually descriptive text is what's displayed not the URL.

**Comment by jrhorn424** [comment]
> I'm just trying to use links in our readmes as they are used on the web. Usually descriptive text is what's displayed not the URL.

I did not understand. Happy to do that!
